//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebIntelimundo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Configuracion()
        {
            this.Corporativo = new HashSet<Corporativo>();
        }
    
        public System.Guid UsuarioID { get; set; }
        public int RolUsuarioID { get; set; }
        public int TipoUsuarioID { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public string CodigoUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Corporativo> Corporativo { get; set; }
    }
}
