//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebIntelimundo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public System.Guid UsuarioID { get; set; }
        public int RolUsuarioID { get; set; }
        public int TipoUsuarioID { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> GeneroID { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public string CodigoUsuario { get; set; }
        public string CorreoPersonal { get; set; }
        public string CorreInstitucional { get; set; }
        public string Celular { get; set; }
        public string TelefonoContacto { get; set; }
        public Nullable<System.Guid> UbicacionID { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int EstatusRegistroID { get; set; }
        public Nullable<System.Guid> CorporativoID { get; set; }
    
        public virtual Corporativo Corporativo { get; set; }
        public virtual Generos Generos { get; set; }
        public virtual RolesUsuarios RolesUsuarios { get; set; }
        public virtual TiposUsuarios TiposUsuarios { get; set; }
        public virtual Ubicaciones Ubicaciones { get; set; }
    }
}
